In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
df = pd.read_csv('/Customer_data - customer_data.csv')

#Dataset overview
print(df.info())
print('-'*90)
print("\nFirst few rows of the dataset:")
display(df.head(10))
print('-'*90)

#Check for missing values
print("\nMissing values in the dataset:")
print(df.isnull().sum())
print('-'*90)

#Check for number of duplicate rows
print("\nNumber of duplicate rows in the dataset:")
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB
None
------------------------------------------------------------------------------------------

First few rows of the dataset:

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
5,9305-CDSKC,Female,0,No,No,8,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.50,Yes
6,1452-KIOVK,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,...,No,No,Yes,No,Month-to-month,Yes,Credit card (automatic),89.10,1949.40,No
7,6713-OKOMC,Female,0,No,No,10,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,No,Mailed check,29.75,301.90,No
8,7892-POOKP,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,...,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes
9,6388-TABGU,Male,0,No,Yes,62,Yes,No,DSL,Yes,...,No,No,No,No,One year,No,Bank transfer (automatic),56.15,3487.95,No

------------------------------------------------------------------------------------------

Missing values in the dataset:
customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64
------------------------------------------------------------------------------------------

Number of duplicate rows in the dataset:
0

In [ ]:
#Only column Total Charges has no value in that cells that has 0 tenure. Hence we can keep the value of cells to 0
df.loc[df['tenure']==0, 'TotalCharges'] = 0

#Replacing 'No phone service' to 'No' in MultipleLines column
df['MultipleLines'] = df['MultipleLines'].replace('No phone service', 'No')
print(f"Unique values in MultipleLines column after replacement is: {df['MultipleLines'].unique()}")

#Replacing 'No internet service' to 'No' in Multiple columns
column_to_replace = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies']
for column in column_to_replace:
    df[column] = df[column].replace('No internet service', 'No')
    print(f"Unique values in {column} column after replacement is: {df[column].unique()}")

Unique values in MultipleLines column after replacement is: ['No' 'Yes']
Unique values in OnlineSecurity column after replacement is: ['No' 'Yes']
Unique values in OnlineBackup column after replacement is: ['Yes' 'No']
Unique values in DeviceProtection column after replacement is: ['No' 'Yes']
Unique values in TechSupport column after replacement is: ['No' 'Yes']
Unique values in StreamingTV column after replacement is: ['No' 'Yes']
Unique values in StreamingMovies column after replacement is: ['No' 'Yes']

In [ ]:
# Converting categorical columns to numeric(one-hot encoding)
df = pd.get_dummies(df,drop_first=True)

# Feature scaling (standardization)
scaler = StandardScaler()
df[['tenure', 'MonthlyCharges', 'TotalCharges']] = scaler.fit_transform(df[['tenure', 'MonthlyCharges', 'TotalCharges']])

#Saving the process file
processed_dataset = 'processed_Customer_dataset.csv'
df.to_csv(processed_dataset, index=False)

print(f"\nProcessed dataset saved to: {processed_dataset}")

Processed dataset saved to: processed_Customer_dataset.csv